[package]
name = "geometry"
description = "Procedural geometry generation library"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "geometry"
[dependencies]

[[example]]
name = "hello_house"
